In [4]:
d = {'x': 'hej', 'y': 'da'}
if 'x' in d:
    print(d['x'])
if 'z' in d:
    print(d['x'], d['y'])

hej


In [14]:
from ..agents import PeUcrlAgent

ImportError: attempted relative import with no known parent package

In [6]:
import numpy as np
x = np.array([1,5,4], dtype=int)
type(x)

numpy.ndarray

In [7]:
raise ValueError('state or action must be an array')

ValueError: state or action must be an array

In [23]:
x = np.array([[1,2,5],[3,4,6]])
print(x)
y = np.reshape(x, np.prod(np.shape(x)))
print(y)
z = np.reshape(y, np.shape(x))
print(z)
print(np.reshape(bin(59)[2:],(2,3)))

[[1 2 5]
 [3 4 6]]
[1 2 5 3 4 6]
[[1 2 5]
 [3 4 6]]


ValueError: cannot reshape array of size 1 into shape (2,3)